[package]
name = "bionic-writer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bionic_writer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
